### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by kyomster** [GreptimeTeam/greptimedb-client-java#60]
I tried to reproduce the example from the [official repo](https://github.com/GreptimeTeam/greptimedb-client-java/blob/main/greptimedb-example/src/main/java/io/greptime/example/QuickStart.java) and with a docker greptime deployed using the following command
`sudo docker run -d --network=host -v "$(pwd)/greptimedb:/tmp/greptimedb" 
--name greptime --rm 
greptime/greptimedb:0.3.0 standalone start 
--http-addr 0.0.0.0:4000 
--rpc-addr 0.0.0.0:4001 
--mysql-addr 0.0.0.0:4002 
--postgres-addr 0.0.0.0:4003 
--opentsdb-addr 0.0.0.0:4242`

But it seems it cannot connect, I get the error bellow
`Exception in thread "main" java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at org.example.Main.runInsert(Main.java:95)
        at org.example.Main.main(Main.java:65)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:539)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:491)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at com.codahale.metrics.Timer.time(Timer.java:151)
        at io.greptime.common.util.DirectExecutor.execute(DirectExecutor.java:37)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:752)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:688)
        at io.grpc.internal.RetriableStream$Sublistener$5.run(RetriableStream.java:986)
        at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
        at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
        at io.grpc.internal.RetriableStream$Sublistener.closed(RetriableStream.java:981)
        at io.grpc.internal.FailingClientStream.start(FailingClientStream.java:61)
        at io.grpc.internal.RetriableStream$StartEntry.runWith(RetriableStream.java:349)
        at io.grpc.internal.RetriableStream.drain(RetriableStream.java:313)
        at io.grpc.internal.RetriableStream.start(RetriableStream.java:390)
        at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:289)
        at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:191)
        at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
        at io.greptime.rpc.interceptors.ContextToHeadersInterceptor$HeaderAttachingClientCall.start(ContextToHeadersInterceptor.java:65)
        at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:345)
        at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:319)
        at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:307)
        at io.grpc.stub.ClientCalls.asyncUnaryCall(ClientCalls.java:77)
        at io.greptime.rpc.GrpcClient.invokeAsync(GrpcClient.java:239)
        at io.greptime.RouterClient.invoke(RouterClient.java:140)
        at io.greptime.RouterClient.invoke(RouterClient.java:122)
        at io.greptime.WriteClient.writeTo(WriteClient.java:166)
        at io.greptime.WriteClient.lambda$write0$4(WriteClient.java:139)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at io.greptime.common.util.SerializingExecutor.drain0(SerializingExecutor.java:101)
        at com.codahale.metrics.Timer.time(Timer.java:151)
        at io.greptime.common.util.SerializingExecutor.drain(SerializingExecutor.java:85)
        at io.greptime.common.util.SerializingExecutor.execute(SerializingExecutor.java:77)
        at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1184)
        at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2320)
        at io.greptime.WriteClient.write0(WriteClient.java:139)
        at io.greptime.WriteClient.lambda$writeBatch$1(WriteClient.java:88)
        at io.greptime.limit.AbstractLimiter.acquireAndDo(AbstractLimiter.java:72)
        at io.greptime.WriteClient.writeBatch(WriteClient.java:88)
        at io.greptime.GreptimeDB.writeBatch(GreptimeDB.java:142)
        at io.greptime.Write.writeBatch(Write.java:57)
        at io.greptime.Write.write(Write.java:39)
        at org.example.Main.runInsert(Main.java:93)
        ... 1 more
        Suppressed: io.greptime.rpc.errors.OnlyErrorMessage: Grpc unary-call got an error, method=greptime.v1.GreptimeDatabase/Handle, target=[1/127.0.0.1:4001], startCall=1695580775237, duration=302 millis, ctx={retries=0, greptimedb.client.id=1, greptimedb.client.version=0.4.0}
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /127.0.0.1:4001
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
        at io.grpc.netty.shaded.io.netty.channel.unix.Socket.connect(Socket.java:351)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:144)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
        at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
        at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
`

My code is available on [Github](https://github.com/kyomster/greptimedb-test)

Thank you.

**Comment by killme2008** [comment]
Hello, what's your os system? 

If it's mac, it looks like the docker's problem. You used the `host` networking for the containers. But in the docker doc, it said:

```
The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac,
 Docker Desktop for Windows, or Docker EE for Windows Server.
```

So if you are using the Mac OSX, may you change the docker command to:

```
docker run  -p 4000-4003:4000-4003 -p 4242:4242 -v "$(pwd)/greptimedb:/tmp/greptimedb" --name greptime --rm greptime/greptimedb:0.3.2 standalone start --http-addr 0.0.0.0:4000 --rpc-addr 0.0.0.0:4001 --mysql-addr 0.0.0.0:4002 --postgres-addr 0.0.0.0:4003 --opentsdb-addr 0.0.0.0:4242
```

And try again? Thank u.

**Comment by evenyag** [comment]
> sudo docker run -d --network=host -v "$(pwd)/greptimedb:/tmp/greptimedb"  --name greptime --rm  greptime/greptimedb:0.3.0

Your image version is quite old. We made some breaking changes between `0.3.0` and `0.4`. The example may also contain features not supported by old versions. You could remove `$(pwd)/greptimedb` and try the `latest` docker image.

https://docs.greptime.com/getting-started/try-out-greptimedb#docker

**Comment by kyomster** [comment]
I have the same error using the 0.4.0 images and the docker port binding explicit.
I am under Ubuntu 22.04

**Comment by evenyag** [comment]
It should be related to this issue https://github.com/grpc/grpc-java/issues/9387

Does removing the `maven-assembly-plugin` plugin solve this?
https://github.com/kyomster/greptimedb-test/blob/2304225658a4b5e54f1aa33126fef24d7b16c9ef/pom.xml#L29-L50

There is a similar question about this issue.
https://stackoverflow.com/questions/73286776/grpc-unsupportedaddresstypeexception-but-only-when-packaged-with-shadowjar

**Comment by kyomster** [comment]
It's OK now, this issue was `maven-assembly-plugin`
Thanks.
